### ISSUE TITLE
list.html 파일의 LOGO 부분의 링크 관련 이슈 제시

### ISSUE THREAD

**Issue by Dev-smiinii** [sangheun969/cruse#14]
##  참조 대상
@HohyunKim-kr @tmdry4530 @sangheun969

## 1. list.html 파일의 LOGO 부분의 링크(랜딩 페이지)가 없음.
* 이유: 첫 index.html 파일이 로그인 화면인 상태임.
* 해당 이슈 관련해서 별도의 페이지를 생성해야 할지 또는 다른 방법이 있을지 논의가 필요한 것으로 파악됨.

```html
<h1><a href="/"></a>LOGO</h1>
``` 

## 2. 참고 사항
* write.html 파일에서는 동일한 부분에서 list.html 파일로 링크해둔 상태임.
* 이슈 논의에 따라서 함께 변동되어야 할 것으로 파악됨.

```html
<h2><a href="./list.html">Diet diary List</a></h2>
```

**Comment by Dev-smiinii** [comment]
##  참조 대상
@tmdry4530 @sangheun969

##  이슈 내용
## 1. 추가된 식별 사항
* list.html의 언어가 영어로 지정된 것으로 파악됨.
```html
<html lang="en">
```

## 2. 참고 사항
* list.html 파일, view.html 파일

```html
<html lang="en">
```

* index.html 파일, write.html 파일, modify.html 파일

```html
<html lang="ko">
```

**Comment by tmdry4530** [comment]
표기언어 수정완료했습니다.

**Comment by Dev-smiinii** [comment]
Commit(ea32830cc03bb76f9cc88601080fb5735a6566f3) 수정 확인 완료

**Comment by Dev-smiinii** [comment]
Commit(https://github.com/sangheun969/cruse/commit/ea32830cc03bb76f9cc88601080fb5735a6566f3) 수정 확인 완료
